<?php

/**
 * @file
 * Contains uw_assetbank.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function uw_assetbank_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the uw_assetbank module.
    case 'help.page.uw_assetbank':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('UW Assetbank custom integration') . '</p>';
      return $output;

    default:
  }
}
